name: Build ddns-go Packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - aarch64_generic
          - arm_cortex-a7
          - arm_cortex-a9
          - mips_24kc
          - mipsel_24kc
          - riscv64_riscv64
          - x86_64
        sdk:
          - openwrt-24.10
          - SNAPSHOT

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build packages
        uses: sbwml/openwrt-gh-action-sdk@go1.25
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-ddns-go
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: |
            bin/packages/${{ matrix.arch }}/packages_ci/*.apk
            bin/packages/riscv64_generic/packages_ci/*.apk
            bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
      - name: Create release archive
        run: |
          if [ "${{ matrix.arch }}" = "riscv64_riscv64" ] && [ "${{ matrix.sdk }}" = "SNAPSHOT" ]; then
            tar -zcvf ${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/riscv64_generic/ packages_ci
          else
            tar -zcvf ${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/ packages_ci
          fi
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          prerelease: false
          artifacts: "${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz"
